### PR TITLE
Fix wrapping issues in ADOPTERS

### PR DESCRIPTION
**Pull request by hardys**
Looks like editor line-wrapping mangled the table formatting

### CODE REVIEW

**Comment by hardys** [comment]
I can't see a way to escape newlines in the table markdown to satisfy MD013 so I disabled it, which seems consistent with https://github.com/metal3-io/metal3-docs/blob/main/hack/markdownlint.sh (not sure if we want to disable the others too?)

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
> I can't see a way to escape newlines in the table markdown to satisfy MD013 so I disabled it, which seems consistent with https://github.com/metal3-io/metal3-docs/blob/main/hack/markdownlint.sh (not sure if we want to disable the others too?)

No, we would not like to disable that, but rather fix it. We can ignore sections like this https://github.com/metal3-io/metal3-docs/blob/dc8e8a64f06aa1ce41be38aa18e93cd095a174ed/docs/user-guide/src/version_support.md?plain=1#L78 and these days there is options in (some versions of, at least) markdownlint to disable line length for tables specifically etc.

Global ignore rules are only there because markdownlint has not been applied from the start of some repos, so the issues has not been fixed yet. Any new content and repos should not add ignore rules in markdownlint.sh.

**Comment by tuminoid** [comment]
> > I can't see a way to escape newlines in the table markdown to satisfy MD013 so I disabled it, which seems consistent with https://github.com/metal3-io/metal3-docs/blob/main/hack/markdownlint.sh (not sure if we want to disable the others too?)
> 
> No, we would not like to disable that, but rather fix it. We can ignore sections like this https://github.com/metal3-io/metal3-docs/blob/dc8e8a64f06aa1ce41be38aa18e93cd095a174ed/docs/user-guide/src/version_support.md?plain=1#L78 and these days there is options in (some versions of, at least) markdownlint to disable line length for tables specifically etc.
> 
> Global ignore rules are only there because markdownlint has not been applied from the start of some repos, so the issues has not been fixed yet. Any new content and repos should not add ignore rules in markdownlint.sh.

Tired to make a quick PR to address it, and it does not seem to work like it used to. I need to take a look later, if its the linter version or config issue.

**Comment by hardys** [comment]
> > > I can't see a way to escape newlines in the table markdown to satisfy MD013 so I disabled it, which seems consistent with https://github.com/metal3-io/metal3-docs/blob/main/hack/markdownlint.sh (not sure if we want to disable the others too?)
> > 
> > 
> > No, we would not like to disable that, but rather fix it. We can ignore sections like this https://github.com/metal3-io/metal3-docs/blob/dc8e8a64f06aa1ce41be38aa18e93cd095a174ed/docs/user-guide/src/version_support.md?plain=1#L78 and these days there is options in (some versions of, at least) markdownlint to disable line length for tables specifically etc.
> > Global ignore rules are only there because markdownlint has not been applied from the start of some repos, so the issues has not been fixed yet. Any new content and repos should not add ignore rules in markdownlint.sh.
> 
> Tired to make a quick PR to address it, and it does not seem to work like it used to. I need to take a look later, if its the linter version or config issue.

Yeah I did try to fix it before disabling, obviously that would be better but I couldn't see how to do it - if you figure it out please tag me on the PR so I can learn for next time :)

**Pull request merged**
