### PR TITLE
add aliases support to all-owners.sh

### PR DESCRIPTION
**Pull request by tuminoid**
This PR does couple of things to all-owners.sh:

1. Update repositories list, removing ironic-agent-image and adding community and ironic-standalone-operator repos.
2. Remove support for any other role than approvers as it is the only meaningful one and required for updating the ALL-OWNERS
3. Add support for aliases via OWNERS_ALIASES

Additionally, update ALL-OWNERS with the new output as we have two new approvers and have lost two old ones.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
